name: Market Price Bot
slug: market_price_bot
version: "1.0.3"
description: Telegram bot for tracking Ozon & Wildberries prices
startup: services
boot: auto
arch:
  - amd64
  - aarch64
  - armv7
  - armhf
options:
  telegram_token: ""
  chat_id: 0
schema:
  telegram_token: str
  chat_id: int
