name: Market Price Bot
version: "1.1.0"
slug: market_price_bot
description: Telegram bot for tracking Ozon & Wildberries prices
arch:
  - aarch64
  - amd64
startup: application
boot: auto
options:
  telegram_token: ""
  ha_url: "http://homeassistant:8123"
  ha_token: ""
schema:
  telegram_token: str
  ha_url: str
  ha_token: str
