name: Market Price Bot
slug: market_price_bot
version: "1.0.6"
description: Telegram bot for tracking Ozon & Wildberries prices
startup: services
boot: auto

arch:
  - aarch64
  - amd64
  - armv7
  - armhf

build_from:
  aarch64: ghcr.io/home-assistant/addon-base-python:3.12
  amd64: ghcr.io/home-assistant/addon-base-python:3.12
  armv7: ghcr.io/home-assistant/addon-base-python:3.12
  armhf: ghcr.io/home-assistant/addon-base-python:3.12

options:
  telegram_token: ""
  chat_id: 0

schema:
  telegram_token: str
  chat_id: int
