name: Market Price Tracker Bot
version: "0.1.0"  # обязательно в кавычках, semver формат!
slug: market_price_bot  # lowercase, только буквы/цифры/_/-
description: Telegram бот для отслеживания цен Ozon/Wildberries
# url/arch опционально, но добавь
arch:
  - aarch64  # для твоей малинки
  - amd64
  - armv7
  - armhf
startup: application
boot: auto
host_network: true
map:
  - config:rw
options:
  TELEGRAM_TOKEN: ""
  PROXY_SERVER: ""
  PROXY_USERNAME: ""
  PROXY_PASSWORD: ""
schema:
  TELEGRAM_TOKEN: str(required)  # required без значения!
  PROXY_SERVER: str?
  PROXY_USERNAME: str?
  PROXY_PASSWORD: str?