name: Market Price Bot
version: "1.0.0"
slug: market_price_bot
description: Telegram bot for tracking Ozon & Wildberries prices
startup: services
boot: auto
arch:
  - amd64
  - armv7
  - armhf
  - aarch64
options:
  telegram_token: ""
  chat_id: ""
schema:
  telegram_token: str
  chat_id: int

